mca.web/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using mca.providex;
using mca.web.Models;
using mca.web.Helpers;
using mca.dal;
using mca.model;

namespace mca.web.Controllers
{
    [Restricted]
    public class ProductsController : Controller
    {
        #region Lazy Object Initializer

        private Lazy<ProductRepository> repository = new Lazy<ProductRepository>(() =>
        {
            var cache = new ProductRepository { };
            return cache;
        });

        public ProductRepository _ProductRepo
        {
            get { return repository.Value; }
        }

        private Lazy<ProdcutDAL> productDAL = new Lazy<ProdcutDAL>(() =>
        {
            var cache = new ProdcutDAL { };
            return cache;
        });

        public ProdcutDAL _ProductDAL
        {
            get { return productDAL.Value; }
        }

        #endregion

        [OutputCache(Duration = 30, VaryByParam = "none")]
        [HttpGet]
        public ActionResult Home()
        {
            return View();
        }

        [OutputCache(Duration = 30, VaryByParam = "none")]
        [HttpGet]
        public ActionResult Search()
        {
            return View();
        }

        [OutputCache(Duration = 30, VaryByParam = "none")]
        [HttpGet]
        public ActionResult Selector()
        {
            return View();
        }

        [OutputCache(Duration = 90, VaryByParam = "productID")]
        [HttpGet]
        public ActionResult Detail(string productID)
        {            
            dynamic _productDetail = _ProductRepo.GetItemDetail(productID);
            ProductViewModel model = new ProductViewModel { Items = new List<ProductViewItem> { } };
            model.ProductId = _productDetail.CI_Item;
            model.Description = !string.IsNullOrEmpty(_productDetail.ItemCodeDesc) ? _productDetail.ItemCodeDesc : string.Empty;
            model.Brand = !string.IsNullOrEmpty(_productDetail.UDF_BRAND) ? _productDetail.UDF_BRAND : "None";          
            
            var SubItems = _ProductRepo.GetItemWareHouse(productID);
            model.Items.AddRange(SubItems.Items.Select(item => new ProductViewItem
            {
                MonthYear = item.MonthYear,
                TopCustomer1 = item.TopCustomer1,
                TopCustomer1Qty = item.TopCustomer1Qty,
                TopCustomer2 = item.TopCustomer2,
                TopCustomer2Qty = item.TopCustomer2Qty,
                TopCustomer3 = item.TopCustomer3,
                TopCustomer3Qty = item.TopCustomer3Qty,
                Items = item.Items.Select(subItem => new ProductViewLineItem
                {
                    Customer1Qty = subItem.Customer1Qty,
                    Customer2Qty = subItem.Customer2Qty,
                    Customer3Qty = subItem.Customer3Qty,
                    WarehouseCode = subItem.WarehouseCode,
                    Transfer = subItem.Transfer,
                    ShippedQuantity = subItem.ShippedQuantity,
                    PurhaseOrder = subItem.PurhaseOrder,
                    QuantityOnHand = subItem.QuantityOnHand,
                    ProjActQuantity = subItem.ProjActQuantity,
                }).ToList(),
            }));

            _productDetail = SubItems = null;
            return View(model);
        }

        [OutputCache(Duration = 30, VaryByParam = "productID")]
        [HttpGet]
        public ActionResult Forecasting(string productID)
        {
            TempData["alert"] = "Oop";           
            ProductForcastingModel model = new ProductForcastingModel { isDataFound = false };
            if (!string.IsNullOrEmpty(productID))
            {
                dynamic _productDetail = _ProductRepo.GetItemDetail(productID);
                model = new ProductForcastingModel { };
                model.ProductId = _productDetail.CI_Item;
                model.Description = !string.IsNullOrEmpty(_productDetail.ItemCodeDesc) ? _productDetail.ItemCodeDesc : "";
                model.Brand = !string.IsNullOrEmpty(_productDetail.UDF_BRAND) ? _productDetail.UDF_BRAND : "None";
                model.isDataFound = true;

                model.List = new List<SelectListItem> { };
                for (int i = 1; i <= 12; i++)
                {
                    var currentmont = string.Format("{0:MMMM}", DateTime.Now.AddMonths(i));
                    model.List.Add(new SelectListItem { Selected = false, Text = currentmont, Value = string.Empty });
                }
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult Forecasting(ProductForcastingModel _data)
        {
            mca.model.ProductUpdateDataModel model = new ProductUpdateDataModel
            {
                ProductCode = _data.ProductId,
                Description = _data.Description,
                isYearly = _data.isYearly == "Annual" ? true : false,
                Defaultvalue = _data.Defaultvalue,
                CreatedBy = Auth.UserID,
                CreatedByName = Auth.Email,
                ModifyBy = Auth.UserID,
                ModifyByName = Auth.Email,
            };

            model.List = new List<mca.model.SelectList> { };
            if (_data.List != null && _data.List.Count() > 0)
            {
                model.List.AddRange(_data.List.Select(item => new mca.model.SelectList
                {
                    Selected = item.Selected,
                    Text = item.Text,
                    Value = model.isYearly ? "3" : item.Value, //only 3 value assign when yearly is selected.
                }));
            }

            var isSuccess = _ProductDAL.AddProduct(model);
            if (string.IsNullOrEmpty(isSuccess.Item2))
            {
                _ProductDAL.AddForecasting(model.List, isSuccess.Item1);
                TempData["alert"] = "success";
            }
            else { TempData["alert"] = "error"; TempData["msg"] = isSuccess.Item2; }
            return View(_data);
        }

        [OutputCache(Duration = 30, VaryByParam = "none")]
        [HttpGet]
        public ActionResult Analytics()
        {
            return View();
        }

        [HttpGet]
        public JsonResult Autocomplete(string Prefix)
        {
            if (string.IsNullOrEmpty(Prefix))
                return null;
            
            var Item = _ProductRepo.GetItemByFilter(Prefix, CustomEnum.SearchByItemCode).Select(s => new
            {
                Name = s[1].ConvertToString(),
                Id = s[0].ConvertToString()
            });

            return Json(Item, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public PartialViewResult _ProductFilter(string filter, string Header)
        {
            ViewBag.Header = Header;
            var Item = _ProductRepo.GetItemByFilter(filter, CustomEnum.SearchByItemCodeDesc).Select(s => new SelectListItem
            {
                Text = s[1].ConvertToString(),
                Value = s[0].ConvertToString()
            });

            return PartialView(Item);
        }

        [OutputCache(Duration = 30, VaryByParam = "itemCode;Month;Year;")]
        [HttpGet]
        public PartialViewResult _GetItemWareHouseDetail(string itemCode, string Month, string Year)
        {
            var Item = _ProductRepo.GetItemWareHouseDetail(itemCode, Month,Year);
            return PartialView(Item);
        }
    }
}

mca.web/Views/Shared/_Footer.cshtml
@if (Auth.isLogin)
{
    <div class="container">
        <div class="row">
            <div class="footer">
                <ul>
                    <li><a href="@Url.Action("Home", "Products")">Home</a></li>
                    <li><a href="@Url.Action("Search", "Products")">Product Search</a></li>
                    <li><a href="@Url.Action("Selector", "Products")">Product Selector</a></li>
                    @if (Auth.RoleName == "WebAdmin" || Auth.RoleName == "Admin")
                    {
                        <li><a href="@Url.Action("Forecasting", "Products")">Forecasting</a></li>
                    }
                    <li><a href="@Url.Action("Analytics", "Products")">Analytics</a></li>
                    @if (Auth.RoleName == "WebAdmin")
                    {
                        <li><a href="@Url.Action("Index", "Account")">Users</a></li>
                    }
                </ul>
            </div>
            <div class="rights">
                <p>© MCA CORPORATION MANUFACTURING COMPANY @DateTime.Now.Year</p>
            </div>
        </div>
    </div>
}

mca.web/Views/Shared/_Header.cshtml
@if (Auth.isLogin)
{
     <!-- Log off row -->
    <div class="container-fluid black-g">
        <div class="container">
            <div class="row">
                <div class="logoff">
                    <i class="fa" aria-hidden="true"> @(Auth.FirstName + " " + Auth.LastName)</i>
                    <i> | </i>
                    <a href="@Url.Action("Logout", "Account")">
                        <i class="fa fa-power-off" aria-hidden="true" title="@(Auth.RoleName)">&nbsp; Log Off</i>
                    </a>
                </div>
            </div>
        </div>
    </div>
}
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">
                <div class="logo"><img class="img-responsive" src="~/Images/logo.jpg" alt="mca corporation" title="MCA-CORPORATION"></div>
            </a>
        </div>
        @if (Auth.isLogin)
        {
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="@Url.Action("Home", "Products")">Home</a></li>
                    <li><a href="@Url.Action("Search", "Products")">Product Search</a></li>
                    <li><a href="@Url.Action("Selector", "Products")">Product Selector</a></li>
                    @if (Auth.RoleName == "WebAdmin" || Auth.RoleName == "Admin")
                    {
                        <li><a href="@Url.Action("Forecasting", "Products")">Forecasting</a></li>
                    }
                    <li><a href="@Url.Action("Analytics", "Products")">Analytics</a></li>
                    @if (Auth.RoleName == "WebAdmin")
                    {
                        <li><a href="@Url.Action("Index", "Account")">Users</a></li>
                    }
                </ul>
            </div>
        }
    </div>
</nav>

mca.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MCA-CORPORATION</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/CustomStyle")
    @Styles.Render("~/Content/jqueryui")
    
    @RenderSection("Styles", required: false)
</head>
<body>
    @{Html.RenderPartial("_Header");}

    <div class="container-fluid">

        @RenderBody()

    </div>

    @{Html.RenderPartial("_Footer");}

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/unobtrusive")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/custom")   

    @RenderSection("scripts", required: false)
</body>
</html>

mca.web/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />   

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>MCA-CORPORATION</title>

    <!-- Bootstrap -->

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/my-style.css" rel="stylesheet" />

</head>
<body class="login-bg">
    <nav class="navbar navbar-default">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand" href="#"><div class="logo"><img class="img-responsive" src="~/Images/logo.jpg" alt="MCA-CORPORATION"></div></a>
            </div>
        </div><!-- /.container-fluid -->
    </nav>

    @RenderBody()

    <div class="container-fluid footer-black">
        <div class="container">
            <div class="row">
                <p>© MCA CORPORATION MANUFACTURING COMPANY @DateTime.Now.Year</p>
            </div>
        </div>
    </div>

    <script src="~/Scripts/jquery-3.1.1.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    <script type="text/javascript">
    $(function () {
        setTimeout(function () { $("#errorMessage").hide(); }, 5000);
    });
    </script>
</body>
</html>